Adaptive Boosting is a boosting ensemble technique used to combine multiple weak classifiers to form strong classifiers

In [1]:
import pandas as pd
import numpy as np 
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
train = pd.read_csv("train.csv")
test = pd.read_csv("test.csv")
train,test

(     PassengerId  Survived  Pclass  \
 0              1         0       3
 1              2         1       1
 2              3         1       3
 3              4         1       1
 4              5         0       3
 ..           ...       ...     ...
 886          887         0       2
 887          888         1       1
 888          889         0       3
 889          890         1       1
 890          891         0       3

                                                   Name     Sex   Age  SibSp  \
 0                              Braund, Mr. Owen Harris    male  22.0      1
 1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
 2                               Heikkinen, Miss. Laina  female  26.0      0
 3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
 4                             Allen, Mr. William Henry    male  35.0      0
 ..                                                 ...     ...   ...    ...
 886                              Montvila, Rev. Juozas    male  27.0      0
 887                       Graham, Miss. Margaret Edith  female  19.0      0
 888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1
 889                              Behr, Mr. Karl Howell    male  26.0      0
 890                                Dooley, Mr. Patrick    male  32.0      0

      Parch            Ticket     Fare Cabin Embarked
 0        0         A/5 21171   7.2500   NaN        S
 1        0          PC 17599  71.2833   C85        C
 2        0  STON/O2. 3101282   7.9250   NaN        S
 3        0            113803  53.1000  C123        S
 4        0            373450   8.0500   NaN        S
 ..     ...               ...      ...   ...      ...
 886      0            211536  13.0000   NaN        S
 887      0            112053  30.0000   B42        S
 888      2        W./C. 6607  23.4500   NaN        S
 889      0            111369  30.0000  C148        C
 890      0            370376   7.7500   NaN        Q

 [891 rows x 12 columns],
      PassengerId  Pclass                                          Name  \
 0            892       3                              Kelly, Mr. James
 1            893       3              Wilkes, Mrs. James (Ellen Needs)
 2            894       2                     Myles, Mr. Thomas Francis
 3            895       3                              Wirz, Mr. Albert
 4            896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)
 ..           ...     ...                                           ...
 413         1305       3                            Spector, Mr. Woolf
 414         1306       1                  Oliva y Ocana, Dona. Fermina
 415         1307       3                  Saether, Mr. Simon Sivertsen
 416         1308       3                           Ware, Mr. Frederick
 417         1309       3                      Peter, Master. Michael J

         Sex   Age  SibSp  Parch              Ticket      Fare Cabin Embarked
 0      male  34.5      0      0              330911    7.8292   NaN        Q
 1    female  47.0      1      0              363272    7.0000   NaN        S
 2      male  62.0      0      0              240276    9.6875   NaN        Q
 3      male  27.0      0      0              315154    8.6625   NaN        S
 4    female  22.0      1      1             3101298   12.2875   NaN        S
 ..      ...   ...    ...    ...                 ...       ...   ...      ...
 413    male   NaN      0      0           A.5. 3236    8.0500   NaN        S
 414  female  39.0      0      0            PC 17758  108.9000  C105        C
 415    male  38.5      0      0  SOTON/O.Q. 3101262    7.2500   NaN        S
 416    male   NaN      0      0              359309    8.0500   NaN        S
 417    male   NaN      1      1                2668   22.3583   NaN        C

 [418 rows x 11 columns])

In [3]:
df =pd.concat([train,test],sort=False)
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0.0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1.0,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1.0,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1.0,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0.0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
413,1305,NaN,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500,NaN,S
414,1306,NaN,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C
415,1307,NaN,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S
416,1308,NaN,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,NaN,S
417,1309,NaN,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,NaN,C

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1309 entries, 0 to 417
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  1309 non-null   int64
 1   Survived     891 non-null    float64
 2   Pclass       1309 non-null   int64
 3   Name         1309 non-null   object
 4   Sex          1309 non-null   object
 5   Age          1046 non-null   float64
 6   SibSp        1309 non-null   int64
 7   Parch        1309 non-null   int64
 8   Ticket       1309 non-null   object
 9   Fare         1308 non-null   float64
 10  Cabin        295 non-null    object
 11  Embarked     1307 non-null   object
dtypes: float64(3), int64(4), object(5)
memory usage: 132.9+ KB

In [6]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
PassengerId,1309.0,655.000000,378.020061,1.00,328.0000,655.0000,982.000,1309.0000
Survived,891.0,0.383838,0.486592,0.00,0.0000,0.0000,1.000,1.0000
Pclass,1309.0,2.294882,0.837836,1.00,2.0000,3.0000,3.000,3.0000
Age,1046.0,29.881138,14.413493,0.17,21.0000,28.0000,39.000,80.0000
SibSp,1309.0,0.498854,1.041658,0.00,0.0000,0.0000,1.000,8.0000
Parch,1309.0,0.385027,0.865560,0.00,0.0000,0.0000,0.000,9.0000
Fare,1308.0,33.295479,51.758668,0.00,7.8958,14.4542,31.275,512.3292

In [23]:
df.isna().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           1
Embarked       0
dtype: int64

In [10]:
df.drop(['Cabin'],axis=1,inplace=True)

In [17]:
#value imputation in age
from sklearn.impute import SimpleImputer
si = SimpleImputer(strategy='mean')
df['Age'] = si.fit_transform(df[['Age']])

In [16]:
df['Survived'] = si.fit_transform(df[['Survived']])

In [24]:
si1 = SimpleImputer(strategy='most_frequent')
df['Embarked'] = si1.fit_transform(df[['Embarked']]).ravel()
df['Fare'] = si1.fit_transform(df[['Fare']]).ravel()

In [27]:

df

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked
0,1,0.000000,3,male,22.000000,1,0,7.2500,S
1,2,1.000000,1,female,38.000000,1,0,71.2833,C
2,3,1.000000,3,female,26.000000,0,0,7.9250,S
3,4,1.000000,1,female,35.000000,1,0,53.1000,S
4,5,0.000000,3,male,35.000000,0,0,8.0500,S
...,...,...,...,...,...,...,...,...,...
413,1305,0.383838,3,male,29.881138,0,0,8.0500,S
414,1306,0.383838,1,female,39.000000,0,0,108.9000,C
415,1307,0.383838,3,male,38.500000,0,0,7.2500,S
416,1308,0.383838,3,male,29.881138,0,0,8.0500,S
417,1309,0.383838,3,male,29.881138,1,1,22.3583,C

In [28]:
from sklearn.preprocessing import OrdinalEncoder
oe = OrdinalEncoder()

In [31]:
df['Sex'] = oe.fit_transform(df[['Sex']])

In [33]:
df['Embarked'] = oe.fit_transform(df[['Embarked']])
df

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked
0,1,0.000000,3,1.0,22.000000,1,0,7.2500,2.0
1,2,1.000000,1,0.0,38.000000,1,0,71.2833,0.0
2,3,1.000000,3,0.0,26.000000,0,0,7.9250,2.0
3,4,1.000000,1,0.0,35.000000,1,0,53.1000,2.0
4,5,0.000000,3,1.0,35.000000,0,0,8.0500,2.0
...,...,...,...,...,...,...,...,...,...
413,1305,0.383838,3,1.0,29.881138,0,0,8.0500,2.0
414,1306,0.383838,1,0.0,39.000000,0,0,108.9000,0.0
415,1307,0.383838,3,1.0,38.500000,0,0,7.2500,2.0
416,1308,0.383838,3,1.0,29.881138,0,0,8.0500,2.0
417,1309,0.383838,3,1.0,29.881138,1,1,22.3583,0.0

In [34]:
df['Survived'] = oe.fit_transform(df[['Survived']])

In [35]:
x = df.drop(['Survived'],axis=1)
y = df['Survived']

In [36]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.3,random_state=0)

In [44]:
from sklearn.ensemble import AdaBoostClassifier
ab = AdaBoostClassifier(n_estimators=45,learning_rate=1,random_state=0)
ab.fit(xtrain,ytrain)

AdaBoostClassifier(learning_rate=1, n_estimators=45, random_state=0)

In [45]:
from sklearn.metrics import accuracy_score
prediction = ab.predict(xtest)
print(prediction)
acc = accuracy_score(prediction,ytest)
print(acc)

[1. 0. 0. 1. 2. 1. 0. 0. 0. 2. 0. 0. 2. 1. 0. 2. 0. 2. 0. 1. 0. 0. 1. 0.
 0. 0. 0. 1. 1. 1. 1. 0. 0. 0. 2. 1. 1. 2. 1. 1. 0. 0. 2. 0. 0. 1. 1. 0.
 1. 1. 2. 2. 1. 1. 2. 1. 0. 0. 0. 0. 0. 0. 1. 1. 1. 0. 0. 1. 1. 0. 0. 0.
 0. 1. 1. 0. 0. 0. 1. 1. 2. 0. 0. 0. 1. 0. 2. 0. 0. 0. 1. 1. 0. 2. 1. 0.
 1. 1. 0. 0. 0. 1. 0. 1. 0. 0. 2. 1. 2. 2. 0. 0. 0. 2. 0. 0. 0. 0. 2. 0.
 0. 0. 0. 0. 2. 1. 0. 0. 2. 2. 1. 0. 0. 0. 0. 1. 0. 1. 0. 1. 0. 0. 1. 2.
 2. 0. 0. 1. 0. 0. 1. 2. 2. 0. 2. 1. 2. 0. 2. 0. 1. 0. 0. 0. 0. 1. 1. 1.
 1. 1. 0. 0. 1. 1. 0. 2. 1. 0. 2. 0. 0. 1. 1. 2. 0. 1. 2. 1. 0. 1. 2. 0.
 0. 2. 0. 1. 2. 0. 1. 0. 0. 1. 0. 0. 2. 0. 2. 2. 2. 1. 1. 0. 2. 0. 0. 0.
 0. 1. 0. 0. 0. 0. 2. 2. 0. 1. 1. 0. 1. 1. 0. 0. 2. 1. 1. 1. 1. 2. 1. 0.
 0. 0. 1. 0. 0. 0. 2. 0. 1. 1. 2. 1. 0. 1. 0. 0. 1. 0. 1. 2. 0. 1. 1. 0.
 1. 1. 0. 1. 0. 1. 2. 2. 0. 0. 1. 0. 0. 2. 1. 1. 0. 0. 0. 0. 1. 1. 1. 1.
 0. 0. 2. 1. 0. 1. 2. 1. 1. 1. 0. 1. 2. 2. 1. 0. 1. 0. 0. 1. 1. 1. 0. 2.
 1. 2. 0. 0. 1. 0. 0. 0. 1. 0. 0. 0. 0. 2. 0. 1. 2. 0. 0. 0. 0. 0. 2. 1.
 0. 2. 2. 0. 0. 0. 0. 0. 0. 1. 1. 0. 1. 0. 0. 0. 1. 0. 0. 1. 0. 0. 1. 0.
 0. 0. 0. 1. 1. 0. 0. 1. 1. 1. 0. 0. 0. 1. 0. 2. 0. 1. 1. 0. 1. 0. 0. 0.
 1. 0. 1. 1. 1. 2. 1. 1. 2.]
0.8575063613231552